// <auto-generated />
using System;
using ApiFinancas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiFinancas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250911093117_tabela-lancamentos")]
    partial class tabelalancamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Financas")
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiFinancas.Domain.Entities.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<int>("StatusLancamento")
                        .HasColumnType("integer");

                    b.Property<int>("TipoLancamento")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioExclusaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioInclusaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioUltimaAlteracaoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.ToTable("Lancamentos", "Financas");
                });

            modelBuilder.Entity("ApiFinancas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeAcesso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioExclusaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioInclusaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioUltimaAlteracaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", "Financas");
                });
#pragma warning restore 612, 618
        }
    }
}
